insert into colors(`color_description_en`,`color_description_ru`) values('Black','Черный');
insert into colors(`color_description_en`,`color_description_ru`) values('Blue','Синий');
insert into colors(`color_description_en`,`color_description_ru`) values('Grey','Серый');
insert into colors(`color_description_en`,`color_description_ru`) values('Pink','Розовый');
insert into colors(`color_description_en`,`color_description_ru`) values('Gold','Золотой');
insert into colors(`color_description_en`,`color_description_ru`) values('Red','Красный');
insert into colors(`color_description_en`,`color_description_ru`) values('Ultraviolet','Ультрафиолет');
insert into colors(`color_description_en`,`color_description_ru`) values('Titan','Титан');
insert into colors(`color_description_en`,`color_description_ru`) values('Copper','Медь');
insert into colors(`color_description_en`,`color_description_ru`) values('Purple','Пурпурный');
insert into colors(`color_description_en`,`color_description_ru`) values('Indigo','Индиго');
insert into colors(`color_description_en`,`color_description_ru`) values('Green','Зеленый');
insert into colors(`color_description_en`,`color_description_ru`) values('Starry Night','Звездное небо');
insert into colors(`color_description_en`,`color_description_ru`) values('White','Белый');
insert into colors(`color_description_en`,`color_description_ru`) values('Silver','Серебряный');
insert into colors(`color_description_en`,`color_description_ru`) values('Space Grey','Космический серый');
insert into colors(`color_description_en`,`color_description_ru`) values('Rose Gold','Розовое золото');
insert into colors(`color_description_en`,`color_description_ru`) values('Brown','Коричневый');
insert into colors(`color_description_en`,`color_description_ru`) values('Violet','Фиолетовый');
insert into colors(`color_description_en`,`color_description_ru`) values('Burgundy','Бордовый');